config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
	devise_for :users
  resources :shows
  resources :movies
  resources :comics
  resources :books
	resources :pages
	resources :users, only: [:show, :index]

#	controller :shows do
#		get :search
#	end

	controller :pages do
		get :home
		get :about
		get :contact
	end

end

app/models/comic.rb
class Comic < ApplicationRecord
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
	include ActionView::Helpers::TextHelper
  before_action :set_comic, only: [:show, :edit, :update, :destroy]

  # GET /comics
  # GET /comics.json
  def index
		if (params[:data] != nil)
			@comic = Comic.new
			@client = Goodreads::Client.new(api_key: "rSkvvZY8Wx27zcj4AfHA", api_secret: "S5WOpmY8pVtaEu1IwNn51DBafjoEIbjuxZdE6sNM")
			@search = @client.search_books(params[:data])
			#@search = @client.search_books("the lord of the rings")
			#puts @search.total_results
			#puts @search
			if (@search.total_results == 1)
				@results = @search
			else
				@results = @search.results.work
			end
			#https://image.tmdb.org/t/p/w300_and_h450_bestv2
		end
    @comics = Comic.all
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
  end

  # GET /comics/new
  def new
    @comic = Comic.new
  end

  # GET /comics/1/edit
  def edit
  end

  # POST /comics
  # POST /comics.json
  def create
		client = Goodreads::Client.new(api_key: "rSkvvZY8Wx27zcj4AfHA", api_secret: "S5WOpmY8pVtaEu1IwNn51DBafjoEIbjuxZdE6sNM")
		comic = client.book_by_isbn(comic_params[:isbn])
		@comic = Comic.new(comic_params)

#		puts book.title
#		puts book.description
#		puts book.work.original_title
#		puts book.num_pages
#		puts book.authors.author.name
#		puts book.publisher

		@comic.description = strip_tags(comic.description)
		puts @comic.description#.gsub(/<br\s*\?>/, '')
		@comic.title = comic.title
		@comic.pages = comic.num_pages
		if (comic.authors.author[0] != nil)
			@comic.author = comic.authors.author[0].name
		else
			@comic.author = comic.authors.author.name
		end
		@comic.comicrating = comic.average_rating
		puts @comic.comicrating

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1
  # PATCH/PUT /comics/1.json
  def update
		respond_to do |format|
			client = Goodreads::Client.new(api_key: "rSkvvZY8Wx27zcj4AfHA", api_secret: "S5WOpmY8pVtaEu1IwNn51DBafjoEIbjuxZdE6sNM")
			comic = client.book_by_isbn(comic_params[:isbn])
			@comic.description = strip_tags(comic.description)
	 		@comic.title = comic.title
	 		@comic.pages = comic.num_pages
	 		@comic.author = comic.authors.author[0].name
	 		@comic.comicrating = comic.average_rating
			@comic.save
			format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
			format.json { render :show, status: :ok, location: @comic }
		end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: 'Comic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comic_params
      params.require(:comic).permit(:title, :description, :author, :isbn, :pages, :user_id)
    end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<%= simple_form_for(@comic) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :author %>
		<%= f.input :pages %>
    <%= f.input :isbn %>
		<%= f.input :user_id, :input_html => { :value => "#{current_user.id}" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comics/edit.html.erb
<h1>Editing Comic</h1>

<%= render 'form', comic: @comic %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<br>
<div class="has-text-centered">
	<strong class="showfont has-text-dark">Your Comics</strong>
</div>

<% averagerating = 0 %>
<% totalcomics = 0 %>
<% totalpages = 0 %>

<body>
	<div class="columns">
		<div class="column"></div>
		<div class="column has-text-centered">
			<br>
			<%= form_with url: "comics", local: true, method: 'get' do |f| %>
			<%= f.text_field :data, :class => "input", placeholder: "Show Title" %>
			<p><br></p>
			<%= f.submit "Search", :class => "button is-primary" %>
			<% end %>
		</div>
		<div class="column"></div>
	</div>

	<% if @results %>
		<div class="container">
			<table class="table is-striped is-hoverable table center">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th><p class="has-text-centered">Title</p></th>
						<th><p class="has-text-centered">Author</p></th>
						<th><p class="has-text-centered">Published</p></th>
						<th></th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% actual_index = 0 %>
					<% if (@search.total_results == "1") %>
					<tr>
						<% if (@results.original_publication_month != nil && @results.original_publication_day != nil && @results.original_publication_year != nil) %>
							<td><p class="has-text-centered"><%= "#{actual_index+= 1}" %></p></td>
							<td><img src=<%=@results.best_book.small_image_url%>></td>
							<td><p class="has-text-centered"><strong><%= @results.best_book.title %></strong></p></td>
							<td><p class="has-text-centered"><%= @results.best_book.author.name %></p></td>
							<td><p class="has-text-centered"><%= @results.original_publication_month %>-<%= @results.original_publication_day %>-<%= @results.original_publication_year %></p></td>
							<td><%= simple_form_for(@comic) do |f| %>
							<%= f.error_notification %>
							<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
								<%= f.hidden_field :isbn, :value => @results.best_book.id%>
								<%= f.hidden_field :user_id, :value => "#{current_user.id}" %>
								<%= f.button :submit, "Add Comic" %>
							<% end %></td>
						<% end %>
					</tr>
					<% else %>
						<% @results.each.with_index(1) do |result, index| %>
						<%= puts @results %>
							<tr>
								<% if (result.original_publication_month != nil && result.original_publication_day != nil && result.original_publication_year != nil) %>
									<td><p class="has-text-centered"><%= "#{actual_index+= 1}" %></p></td>
									<td><img src=<%=result.best_book.small_image_url%>></td>
									<td><p class="has-text-centered"><strong><%= result.best_book.title %></strong></p></td>
									<td><p class="has-text-centered"><%= result.best_book.author.name %></p></td>
									<td><p class="has-text-centered"><%= result.original_publication_month %>-<%= result.original_publication_day %>-<%= result.original_publication_year %></p></td>
									<td><%= simple_form_for(@comic) do |f| %>
									<%= f.error_notification %>
									<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
										<%= f.hidden_field :isbn, :value => result.best_book.id%>
										<%= f.hidden_field :user_id, :value => "#{current_user.id}" %>
										<%= f.button :submit, "Add Comic" %>
									<% end %></td>
								<% end %>
								<% if (actual_index >= 10) %>
									<% break %>
								<% end %>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>

	<div class="level">
		<div class="level-item">
			<%= link_to 'Back', "home", class: "button is-danger" %>
		</div>
		<div class="level-item">
			<%= link_to 'New Comic', new_comic_path, class: "button is-success" %>
		</div>
	</div>


	<div class="container">
		<table class="table is-striped is-hoverable table center">
			<thead>
				<tr>
					<th></th>
					<th class="has-text-centered">Title</th>
					<th class="has-text-centered">Description</th>
					<th class="has-text-centered">Author</th>
					<th class="has-text-centered">Rating</th>
					<th class="has-text-centered">Pages</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @comics.each.with_index(0) do |comic, index| %>
				<tr>
					<% if comic.user_id == current_user.id %>
					<td><%= "#{index}" %></td>
					<td><p class="has-text-centered"><strong><%= link_to "#{comic.title}", comic %></strong></p></td>
					<td><p class="has-text-centered"><%= truncate comic.description, length: 100, seperator: /\w+/ %></p></td>
					<td><p class="has-text-centered"><%= comic.author %></p></td>
					<td><p class="has-text-centered"><%= comic.comicrating %></p></td>
					<% averagerating+= comic.comicrating %>
					<td><p class="has-text-centered"><%= comic.pages %></p></td>
					<% totalpages+= comic.pages %>
					<% totalcomics+= 1 %>
					<td><%= link_to 'Edit', edit_comic_path(comic) %></td>
					<td><%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>
		<table class="table is-striped is-hoverable table center">
			<thead>
				<tr>
					<th>Stats:</th>
					<th>Comics</th>
					<th>Average Rating</th>
					<th>Total Pages</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<td>Totals:</td>
					<td><p class="has-text-centered"><%= totalcomics %></p></td>
					<td><p class="has-text-centered"><%= (averagerating / totalcomics).round(2) %></p></td>
					<td><p class="has-text-centered"><%= totalpages %></p></td>
				</tr>
			</tbody>
		</table>
	</div>
</body>

app/views/comics/new.html.erb
<h1>New Comic</h1>

<%= render 'form', comic: @comic %>

<%= link_to 'Back', comics_path %>

app/views/comics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @comic.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comic.author %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @comic.comicrating %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @comic.pages %>
</p>

<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>