config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
	devise_for :users
  resources :shows
  resources :movies
  resources :comics
  resources :books
	resources :pages
	resources :users, only: [:show, :index]

#	controller :shows do
#		get :search
#	end

	controller :pages do
		get :home
		get :about
		get :contact
	end

end

app/views/pages/about.html.erb
<br>
<div class="comlumns is-vcentered">
	<div class="column has-text-centered">
		This Product uses the TMDb API but is not endorsed or certified by TMDb.
	</div>
	<div class="column">
		<figure class="is-flex is-vertical-center">
			<img src="https://www.themoviedb.org/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg">
		</figure>
	</div>
</div>

app/views/pages/home.html.erb
<body>
	<section class="section">
		<p class="has-text-centered title is-2">Your Lists</p>
		<div class="container">
			<div class="columns is-vcentered">
				<div class="column">
					<%= link_to movies_path, class: "navbar_item" do %>
					<div class="button is-large is-fullwidth">
						Movies
					</div>
					<% end %>
				</div>
				<div class="column">
					<%= link_to shows_path, class: "navbar_item" do %>
					<div class="button is-large is-fullwidth">
						Shows
					</div>
					<% end %>
				</div>
				<div class="column">
					<%= link_to books_path, class: "navbar_item" do %>
					<div class="button is-large is-fullwidth">
						Books
					</div>
					<% end %>
				</div>
				<div class="column">
					<%= link_to comics_path, class: "navbar_item" do %>
					<div class="button is-large is-fullwidth">
						Comics
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</section
</body>