config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
	devise_for :users
  resources :shows
  resources :movies
  resources :comics
  resources :books
	resources :pages
	resources :users, only: [:show, :index]

#	controller :shows do
#		get :search
#	end

	controller :pages do
		get :home
		get :about
		get :contact
	end

end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	include ActionView::Helpers::TextHelper
  before_action :set_book, only: [:show, :edit, :update, :destroy]
	require 'openlibrary'

  # GET /books
  # GET /books.json
  def index
		if (params[:data] != nil)
			@book = Book.new
			@client = Goodreads::Client.new(api_key: "rSkvvZY8Wx27zcj4AfHA", api_secret: "S5WOpmY8pVtaEu1IwNn51DBafjoEIbjuxZdE6sNM")
			@search = @client.search_books(params[:data])
			#@search = @client.search_books("the lord of the rings")
			@results = @search.results.work
			#https://image.tmdb.org/t/p/w300_and_h450_bestv2
		end

    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
		client = Goodreads::Client.new(api_key: "rSkvvZY8Wx27zcj4AfHA", api_secret: "S5WOpmY8pVtaEu1IwNn51DBafjoEIbjuxZdE6sNM")
		book = client.book_by_isbn(book_params[:isbn])
		@book = Book.new(book_params)

#		puts book.title
#		puts book.description
#		puts book.work.original_title
#		puts book.num_pages
#		puts book.authors.author.name
#		puts book.publisher

		@book.titlelong = book.title
		@book.description = strip_tags(book.description)
		puts @book.description#.gsub(/<br\s*\?>/, '')
		@book.title = book.work.original_title
		@book.pages = book.num_pages
		@book.bookrating = book.average_rating
		@book.author = book.authors.author.name
		@book.publisher = book.publisher

		#book.search("9780545790352", 5)
		#puts book.books.first.get_title
		#@show = Show.new(show_params)
		#@show.title = result["original_name"]
		#@show.description = result["overview"]
		#@show.seasons = result["number_of_seasons"]
		#@show.episodes = result["number_of_episodes"]
		#@show.episoderuntime = result["episode_run_time"].dig(0)
		#@show.showrating = result["vote_average"]
		#@show.airdate = result["first_air_date"]


    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
		respond_to do |format|
			client = Goodreads::Client.new(api_key: "rSkvvZY8Wx27zcj4AfHA", api_secret: "S5WOpmY8pVtaEu1IwNn51DBafjoEIbjuxZdE6sNM")
			book = client.book_by_isbn(book_params[:isbn])
			@book.titlelong = book.title
			@book.description = strip_tags(book.description)
			@book.title = book.work.original_title
			@book.pages = book.num_pages
			@book.bookrating = book.average_rating
			@book.author = book.authors.author.name
			@book.publisher = book.publisher
			@book.save
			format.html { redirect_to @book, notice: 'Book was successfully updated.' }
			format.json { render :show, status: :ok, location: @book }
		end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :author, :isbn, :titlelong, :publisher, :pages, :bookrating, :user_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
		<%= f.input :isbn %>
    <%= f.input :title %>
		<%= f.input :titlelong %>
		<%= f.input :description %>
		<%= f.input :author %>
		<%= f.input :publisher %>
		<%= f.input :pages %>
		<%= f.input :user_id, :input_html => { :value => "#{current_user.id}" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<br>
<div class="has-text-centered">
	<strong class="showfont has-text-dark">Your Books</strong>
</div>

<% averagerating = 0 %>
<% totalbooks = 0 %>
<% totalpages = 0 %>

<body>
	<div class="columns">
		<div class="column"></div>
		<div class="column has-text-centered">
			<br>
			<%= form_with url: "books", local: true, method: 'get' do |f| %>
			<%= f.text_field :data, :class => "input", placeholder: "Show Title" %>
			<p><br></p>
			<%= f.submit "Search", :class => "button is-primary" %>
			<% end %>
		</div>
		<div class="column"></div>
	</div>

	<% if @results %>
	<%= puts @results %>
  <%= puts "hello" %>

		<div class="container">
			<table class="table is-striped is-hoverable table center">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th><p class="has-text-centered">Title</p></th>
						<th><p class="has-text-centered">Author</p></th>
						<th><p class="has-text-centered">Published</p></th>
						<th></th>
						<th colspan="3"></th>
					</tr>
				</thead>
					<tbody>
					<% actual_index = 0 %>
					<% @results.each.with_index(1) do |result, index| %>
					<%= puts result %>
						<tr>
							<% if (result.original_publication_month != nil && result.original_publication_day != nil && result.original_publication_year != nil) %>
								<td><p class="has-text-centered"><%= "#{actual_index+= 1}" %></p></td>
								<td><img src=<%=result.best_book.small_image_url%>></td>
								<td><p class="has-text-centered"><strong><%= result.best_book.title %></strong></p></td>
								<td><p class="has-text-centered"><%= result.best_book.author.name %></p></td>
								<td><p class="has-text-centered"><%= result.original_publication_month %>-<%= result.original_publication_day %>-<%= result.original_publication_year %></p></td>
								<td><%= simple_form_for(@book) do |f| %>
								<%= f.error_notification %>
								<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
									<%= f.hidden_field :isbn, :value => result.best_book.id%>
									<%= f.hidden_field :user_id, :value => "#{current_user.id}" %>
									<%= f.button :submit, "Add Book" %>
								<% end %></td>
							<% end %>
							<% if (actual_index >= 10) %>
								<% break %>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>

	<div class="level">
		<div class="level-item">
			<%= link_to 'Back', "home", class: "button is-danger" %>
		</div>
		<div class="level-item">
			<%= link_to 'New Book', new_book_path, class: "button is-success" %>
		</div>
	</div>

	<div class="container">
		<table class="table is-striped is-hoverable is-narrow table center">
			<thead>
				<tr>
					<th></th>
					<th class="has-text-centered">Title</th>
					<th class="has-text-centered">Description</th>
					<th class="has-text-centered">Author</th>
					<th class="has-text-centered">Rating</th>
					<th class="has-text-centered">Pages</th>
					<th>ID</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each.with_index(1) do |book, index| %>
				<tr>
					<% if book.user_id == current_user.id %>
					<td><%= "#{index}" %></td>
					<td><p class="has-text-centered"><strong><%= link_to "#{book.title}", book %></strong></p></td>
					<td><p class="has-text-centered"><%= truncate book.description, length: 90, seperator: /\w+/ %></p></td>
					<td><p class="has-text-centered"><%= book.author %></p></td>
					<td><p class="has-text-centered"><%= book.bookrating %></p></td>
					<% averagerating+= book.bookrating %>
					<td><p class="has-text-centered"><%= book.pages %></p></td>
					<% totalpages+= book.pages %>
					<% totalbooks+= 1 %>
					<td><%= book.user_id %></td>
					<td><%= link_to 'Edit', edit_book_path(book) %></td>
					<td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>
		<table class="table is-striped is-hoverable table center">
			<thead>
				<tr>
					<th>Stats:</th>
					<th>Books</th>
					<th>Average Rating</th>
					<th>Total Pages</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<td>Totals:</td>
					<td><p class="has-text-centered"><%= totalbooks %></p></td>
					<td><p class="has-text-centered"><%= (averagerating / totalbooks).round(2) %></p></td>
					<td><p class="has-text-centered"><%= totalpages %></p></td>
				</tr>
			</tbody>
		</table>
	</div>
</body>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong><br>
  <%= @book.title %><br>
	<strong>Author:</strong><br>
	<%= @book.author %><br>
	<strong>Description:</strong><br>
	<%= @book.description %><br>
	<strong>Pages:</strong><br>
	<%= @book.pages %><br>
	<strong>ID:</strong><br>
	<%= @book.user_id %><br>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>